name: Action Sample

on:
  push:
    branches:
      - main

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: execute echo command
        run: echo "Hello World!"
      - name: execute echo command2
        run: echo "Hello World!2"